# This script is used to move the trajectory files from the image folders in the external hard drive (vorg) to the
# local folder

# I use it separately for each fluorophore used in the experiment as py4bleaching needs to be run separately on each
# differently labelled molecule set

# It also creates a new folder structure

# Output folder structure generated by this script (one folder per concentration, with coloc and non-coloc
# subfolders; the file prefix comes from the `filetype` set for each entry):
#
# imagejresults-647/                     (output_folder, relative to the R working directory)
# └── aBc3D/
#     ├── 1uM/
#     │   ├── coloc/
#     │   │   ├── <filetype>1.csv
#     │   │   ├── <filetype>2.csv
#     │   │   └── ...
#     │   └── non-coloc/
#     │       └── <filetype>1.csv ...
#     ├── 50nM/   (coloc/ and non-coloc/)
#     ├── 100nM/  (coloc/ and non-coloc/)
#     ├── 250nM/  (coloc/ and non-coloc/)
#     └── 500nM/  (coloc/ and non-coloc/)
#

library(fs)

# change these for experiment
input_folder <- "Z:/Chaperone_subgroup/NicolaA/Fibrils with sHsps/20260203"

experiment_date   <- "20260203"
parent_folder_local   <- paste0("C:/Nicola/UNIVERSITY/PhD/SM/Fibrils and sHsps/", experiment_date, "/")
setwd(parent_folder_local)

output_folder <- "imagejresults"

if (!dir_exists(output_folder)) {
  dir_create(output_folder)
}

# can change based on proteins in experiment. Need separate folder for coloc and non-coloc as that is how it was set up in the ImageJ scripts to export

aBc3D_1uM_coloc <- 'aBc3D_1uM_coloc'
aBc3D_50nM_coloc <- 'aBc3D_50nM_coloc'
aBc3D_100nM_coloc <- 'aBc3D_100nM_coloc'
aBc3D_250nM_coloc <- 'aBc3D_250nM_coloc'
aBc3D_500nM_coloc <- 'aBc3D_500nM_coloc'

aBc3D_1uM_noncoloc <- 'aBc3D_1uM_non-coloc'
aBc3D_50nM_noncoloc <- 'aBc3D_50nM_non-coloc'
aBc3D_100nM_noncoloc <- 'aBc3D_100nM_non-coloc'
aBc3D_250nM_noncoloc <- 'aBc3D_250nM_non-coloc'
aBc3D_500nM_noncoloc <- 'aBc3D_500nM_non-coloc'

# change these for the experiment you're using
folders <- list(
  "1uM_aBc3D/20260203_140658_320/AF647 photobleach/coloc_trajectories/"   = list(new_folder = "aBc3D/1uM/coloc/",   filetype = aBc3D_1uM_coloc),
  "1uM_aBc3D/20260203_140658_320/AF647 photobleach/non-coloc_trajectories/647/"   = list(new_folder = "aBc3D/1uM/non-coloc/",   filetype = aBc3D_1uM_noncoloc),
  
  "50nM_aBc3D/20260203_113251_325/AF647 photobleach/coloc_trajectories/"  = list(new_folder = "aBc3D/50nM/coloc/",  filetype = aBc3D_50nM_coloc),
  "50nM_aBc3D/20260203_113251_325/AF647 photobleach/non-coloc_trajectories/647"  = list(new_folder = "aBc3D/50nM/non-coloc/",  filetype = aBc3D_50nM_noncoloc),
  
  "100nM_aBc3D/20260203_110049_245/AF647 photobleach/coloc_trajectories/"  = list(new_folder = "aBc3D/100nM/coloc/",  filetype = aBc3D_100nM_coloc),
  "100nM_aBc3D/20260203_110049_245/AF647 photobleach/non-coloc_trajectories/647/"  = list(new_folder = "aBc3D/100nM/non-coloc/",  filetype = aBc3D_100nM_noncoloc),
  
  "250nM_aBc3D/20260203_102907_567/AF647 photobleach/coloc_trajectories/"  = list(new_folder = "aBc3D/250nM/coloc/",  filetype = aBc3D_250nM_coloc),
  "250nM_aBc3D/20260203_102907_567/AF647 photobleach/non-coloc_trajectories/647/"  = list(new_folder = "aBc3D/250nM/non-coloc/",  filetype = aBc3D_250nM_noncoloc),
  
  "500nM_aBc3D/220260203_143941_688/AF647 photobleach/coloc_trajectories/"  = list(new_folder = "aBc3D/500nM/coloc/",  filetype = aBc3D_500nM_coloc),
  "500nM_aBc3D/20260203_143941_688/AF647 photobleach/non-coloc_trajectories/647/"  = list(new_folder = "aBc3D/500nM/non-coloc/",  filetype = aBc3D_500nM_noncoloc)
  
)


for (old_folder in names(folders)) {
  
  new_folder <- folders[[old_folder]]$new_folder
  filetype   <- folders[[old_folder]]$filetype
  
  old_path <- file.path(input_folder, old_folder)
  new_path <- file.path(output_folder, new_folder)
  
  # create the subfolders (e.g. imagejresults/aBc3D/250nM/non-coloc/)
  if (!dir_exists(new_path)) {
    dir_create(new_path)
  }
  
  if (!dir_exists(old_path)) {
    warning("Missing input folder: ", old_path)
    next
  }
  
  old_files <- list.files(old_path, pattern = "\\.csv$")
  if (length(old_files) == 0) warning("No csv files in: ", old_path)
  
  # number immediately after the '#'
  has_number <- grepl("#\\d+", old_files)
  file_numbers <- ifelse(has_number, sub(".*#(\\d+).*", "\\1", old_files), NA)
  
  if (any(!has_number)) {
    warning("No #number found in: ", paste(old_files[!has_number], collapse = ", "))
  }
  if (anyDuplicated(file_numbers[has_number])) {
    warning("Duplicate numbers in ", old_path, ", later files will overwrite earlier ones")
  }
  
  for (x in which(has_number)) {
    file_copy(
      path = file.path(old_path, old_files[x]),
      new_path = file.path(new_path, paste0(filetype, file_numbers[x], ".csv")),
      overwrite = TRUE
    )
  }
}